//! Golden corpus parity for the checklist parser. Expected JSON in
//! `tests/golden/expected/` was generated by the Python `parse_checklist`; this
//! test asserts the Rust parser produces byte-identical canonical JSON for each
//! success case, and matching errors for the error cases.

use std::fs;
use std::path::PathBuf;

use review_kb::checklist::parse_checklist;
use review_kb::errors::ErrorCode;
use review_kb::json_util::canonical_json;
use review_kb::models::Checklist;
use serde_json::{json, Value};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Mirror of the Python `dump(cl)` helper used to generate the golden files.
fn dump(cl: &Checklist) -> Value {
    let rules: Vec<Value> = cl
        .rules
        .iter()
        .map(|r| {
            json!({
                "key": r.key,
                "summary": r.summary,
                "content": r.content,
                "tags": r.tags,
                "paths": r.paths,
                "languages": r.languages,
                "source_rule_hash": r.source_rule_hash,
            })
        })
        .collect();
    json!({
        "schema_version": cl.schema_version,
        "checklist_version": cl.checklist_version,
        "global_description": cl.global_description,
        "content_hash": cl.content_hash,
        "rules": rules,
    })
}

#[test]
fn golden_success_cases_match_python_byte_for_byte() {
    let expected_dir = manifest_dir().join("tests/golden/expected");
    let cases_dir = manifest_dir().join("tests/golden/cases");
    let mut checked = 0usize;
    for entry in fs::read_dir(&expected_dir).expect("expected dir exists") {
        let entry = entry.unwrap();
        let name = entry.file_name().into_string().unwrap();
        let stem = name.strip_suffix(".json").unwrap_or(&name);
        let case = cases_dir.join(format!("{stem}.md"));
        let expected = fs::read_to_string(entry.path()).unwrap();
        let cl = parse_checklist(&case)
            .unwrap_or_else(|e| panic!("{stem} should parse (Python did): {e:?}"));
        let got = canonical_json(&dump(&cl));
        assert_eq!(got, expected, "byte mismatch in golden case {stem}");
        checked += 1;
    }
    assert!(
        checked >= 4,
        "expected at least 4 golden success cases, found {checked}"
    );
}

#[test]
fn setext_rule_heading_errors_like_python() {
    // A `---` setext underline sits between the heading and the fence, so both
    // Python and Rust reject with "metadata block must appear before rule content".
    let case = manifest_dir().join("tests/golden/cases/setext.md");
    let err = parse_checklist(&case).expect_err("setext case must error");
    assert_eq!(err.code, ErrorCode::ChecklistInvalid);
    assert_eq!(
        err.message,
        "rule SEC-001 metadata block must appear before rule content"
    );
}

#[test]
fn mixed_setext_second_rule_errors_like_python() {
    let case = manifest_dir().join("tests/golden/cases/mixed.md");
    let err = parse_checklist(&case).expect_err("mixed case must error");
    assert_eq!(err.code, ErrorCode::ChecklistInvalid);
    assert_eq!(
        err.message,
        "rule SECOND metadata block must appear before rule content"
    );
}
